language: php
os:
  - linux
  - osx
  - windows
php:
  - '8.1'
  - hhvm # on Trusty only
  - nightly
before_script:
  - composer install --ignore-platform-reqs
script:
  - ./vendor/bin/phpunit
notifications:
  email: false
